AWSTemplateFormatVersion: 2010-09-09
Description: 'CloudFormation template to deploy all the required services for the multi-account SQLServer License Tracking Solution'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: 'Inventory collection' 
        Parameters:
          - BucketName
          - BucketRegion
          - OrganizationId
      - 
        Label: 
          default: 'Automation Documents'
        Parameters: 
          - SQLServerEELicenseConfiguration
          - SQLServerSTDLicenseConfiguration
          - SQLServerWEBLicenseConfiguration
          - SQLServerEXPLicenseConfiguration
          - SQLServerDEVLicenseConfiguration
          - TagKey
          - TagValue
          - ManagementAccountId
          - TargetRegions
          - TargetOUs
    ParameterLabels:
      SQLServerEELicenseConfiguration:
        default: 'Enterprise Edition'
      SQLServerSTDLicenseConfiguration:
        default: 'Standard Edition'
      SQLServerWEBLicenseConfiguration:
        default: 'Web Edition'
      SQLServerEXPLicenseConfiguration:
        default: 'Express Edition'
      SQLServerDEVLicenseConfiguration:
        default: 'Developer Edition'
      TagKey:
        default: 'TagKey'
      TagValue:
        default: 'TagValue'
      ManagementAccountId:
        default: 'ManagementAccountId'
      TargetOUs:
        default: 'TargetOUs'
      TargetRegions:
        default: 'TargetRegions'
      BucketName:
        default: 'BucketName'
      BucketRegion:
        default: 'BucketRegion'
      OrganizationId:
        default: 'OrganizationId'
Resources:
  InventoryCollectionStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        BucketName: !Ref BucketName
        BucketRegion: !Ref BucketRegion
        OrganizationId: !Ref OrganizationId
      TemplateURL: https://s3.amazonaws.com/sql-lts-cfn-templates/SQLServerLTS-S3BucketForInventoryCollectionStack.yaml
  SecondaryAutomationDocumentStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        ManagementAccountId: !Ref ManagementAccountId
        TargetOUs: !Ref TargetOUs
        TargetRegions: !Ref TargetRegions
      TemplateURL: https://s3.amazonaws.com/sql-lts-cfn-templates/SQLServerLTS-SecondaryAutomationDocument.yaml
  PrimaryAutomationDocumentStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        TagKey : !Ref TagKey
        TagValue : !Ref TagValue
        SQLServerEELicenseConfiguration: !Ref SQLServerEELicenseConfiguration
        SQLServerSTDLicenseConfiguration: !Ref SQLServerSTDLicenseConfiguration
        SQLServerWEBLicenseConfiguration: !Ref SQLServerWEBLicenseConfiguration
        SQLServerEXPLicenseConfiguration: !Ref SQLServerEXPLicenseConfiguration
        SQLServerDEVLicenseConfiguration: !Ref SQLServerDEVLicenseConfiguration
      TemplateURL: https://s3.amazonaws.com/sql-lts-cfn-templates/SQLServerLTS-PrimaryAutomationDocument.yaml
Parameters:
  OrganizationId:
    Description: AWS Organization ID.
    Type: String
    AllowedPattern: '^[o]+(-[a-z0-9]+)*$'
    ConstraintDescription: Provide a valid Organization ID (for eg. o-abc5drtefg)
  TargetOUs:
    Description: Organization Unit (OU) IDs which are in scope for this solution in a comma-separated format (for eg. ou-abc1-abc12ab1,ou-def2-def12de1).
    Type: String
    Default: ou-abc1-abc12ab1
  TargetRegions:
    Type: String
    Description: AWS Regions that is in scope for this solution in comma-separated format (for eg. ap-southeast-2, us-east-1).
    Default: ap-southeast-2,us-east-1
  TagKey:
    Description: (Required) This parameter is required if you want to target all managed instances using tags
    Type: String
    Default: 'LicenseTrackingSolution-ManagedInstance'
  TagValue:
    Description: (Required) This parameter is required if you want to target all managed instances using tags
    Type: String
    Default: 'true'
  ManagementAccountId:
    Description: (Required) Management/Root AWS Account ID from where this solution will be executed. If you are using AWS Organizations then you need to specify the root/management account.
    Type: String
    Default: '123456789012'
  SQLServerEELicenseConfiguration:
    Description: License Configuration ARN for SQL Server Enterprise Edition
    Type: String
    Default: '-'
    AllowedPattern: '-|arn:aws:license-manager:[a-z0-9-]*[-]\d:[0-9]{12}:license-configuration:lic-[a-z0-9]*$'
    ConstraintDescription: Provide a valid License Manager Configuration ARN for SQL Enterprise Edition or leave it as -
  SQLServerSTDLicenseConfiguration:
    Description: License Configuration ARN for SQL Server Standard Edition
    Type: String
    Default: '-'
    AllowedPattern: '-|arn:aws:license-manager:[a-z0-9-]*[-]\d:[0-9]{12}:license-configuration:lic-[a-z0-9]*$'
    ConstraintDescription: Provide a valid License Manager Configuration ARN for SQL Standard Edition or leave it as -
  SQLServerWEBLicenseConfiguration:
    Description: License Configuration ARN for SQL Server Web Edition
    Type: String
    Default: '-'
    AllowedPattern: '-|arn:aws:license-manager:[a-z0-9-]*[-]\d:[0-9]{12}:license-configuration:lic-[a-z0-9]*$'
    ConstraintDescription: Provide a valid License Manager Configuration ARN for SQL Web Edition or leave it as -
  SQLServerEXPLicenseConfiguration:
    Description: License Configuration ARN for SQL Server Express Edition
    Type: String
    Default: '-'
    AllowedPattern: '-|arn:aws:license-manager:[a-z0-9-]*[-]\d:[0-9]{12}:license-configuration:lic-[a-z0-9]*$'
    ConstraintDescription: Provide a valid License Manager Configuration ARN for SQL Express Edition or leave it as -
  SQLServerDEVLicenseConfiguration:
    Description: License Configuration ARN for SQL Server Developer Edition
    Type: String
    Default: '-'
    AllowedPattern: '-|arn:aws:license-manager:[a-z0-9-]*[-]\d:[0-9]{12}:license-configuration:lic-[a-z0-9]*$'
    ConstraintDescription: Provide a valid License Manager Configuration ARN for SQL Developer Edition or leave it as -
  BucketName:
    Description: Name for the S3 bucket that will be used to aggregate the Inventory data.
    Type: String
    AllowedPattern: '^[a-z]+(-[a-z]+)*$'
    ConstraintDescription: Provide a valid name for S3 bucket
  BucketRegion:
    Description: AWS Region where the S3 bucket should be deployed into, for eg. ap-southeast-2
    Type: String