AWSTemplateFormatVersion: 2010-09-09
Description: >-
  To create and configure an Amazon S3 bucket for resource data sync for multiple accounts defined in AWS Organizations
Parameters:
  BucketName:
    Description: Name of the S3 bucket where the aggregated data will be stored.
    Type: String
  BucketRegion:
    Description: AWS Region where the S3 bucket will be created in for eg. ap-southeast-2.
    Type: String
  OrganizationID:
    Description: AWS Organization ID.
    Type: String
  Resources:
    S3Bucket:
      Type: 'AWS::S3::Bucket'
      DeletionPolicy: Retain
      Properties:
        BucketName: !Ref BucketName
    S3BucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
          - 
            Sid: "SSMBucketPermissionsCheck"
            Effect: "Allow"
            Principal: 
              Service: "ssm.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}"
          - 
            Sid: " SSMBucketDelivery"
            Effect: "Allow"
            Principal: 
              Service: "ssm.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*/accountid=*/*"
            Condition: 
              StringEquals: 
                "s3:RequestObjectTag/OrgId": 
                  !Sub 
                    - "${OrgID}"
                    - { OrgID: !Ref OrganizationID}
                "s3:x-amz-acl": "bucket-owner-full-control"
          - 
            Sid: " SSMBucketDeliveryTagging"
            Effect: "Allow"
            Principal: 
              Service: "ssm.amazonaws.com"
            Action: "s3:PutObjectTagging"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*/accountid=*/*"



