AWSTemplateFormatVersion: 2010-09-09
Description: 'CloudFormation stackset template to deploy Resource Data Sync to collect inventory data for SQLServer License Tracking Solution'
Parameters:
  BucketName:
    Description: The name of the S3 bucket where the aggregated data is stored.
    Type: String
  BucketRegion:
    Description: The AWS Region with the S3 bucket targeted by the Resource Data Sync for eg. ap-southeast-2
    Type: String
  BucketPrefix:
    Description: An Amazon S3 prefix for the bucket.
    Type: String
Resources:
  SecondarySSMDocument:
    Type: 'AWS::SSM::ResourceDataSync'
    Properties:
      SyncName: 
        "SQLServerLTS-ResourceDataSync"
      BucketName: 
        !Ref BucketName
      BucketRegion: 
        !Ref BucketRegion
      SyncFormat: 
        "JsonSerDe"
      BucketPrefix: 
        !Ref BucketPrefix