AWSTemplateFormatVersion: 2010-09-09
Description: 'CloudFormation template to deploy all the required services for the multi-account SQLServer License Tracking Solution'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: 'Inventory collection' 
        Parameters:
          - BucketName
          - BucketRegion
          - OrganizationId
      - 
        Label: 
          default: 'Automation Documents'
        Parameters: 
          - TagKey
          - TagValue
          - ManagementAccountId
          - TargetRegions
          - TargetOUs
    ParameterLabels:
      TagKey:
        default: 'TagKey'
      TagValue:
        default: 'TagValue'
      ManagementAccountId:
        default: 'ManagementAccountId'
      TargetOUs:
        default: 'TargetOUs'
      TargetRegions:
        default: 'TargetRegions'
      BucketName:
        default: 'BucketName'
      BucketRegion:
        default: 'BucketRegion'
      OrganizationId:
        default: 'OrganizationId'
Resources:
  InventoryCollectionStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        BucketName: !Ref BucketName
        BucketRegion: !Ref BucketRegion
        OrganizationId: !Ref OrganizationId
      TemplateURL: https://sql-lts-cfn-templates.s3-ap-southeast-2.amazonaws.com/SQLServerLTS-S3BucketForInventoryCollectionStack.yaml
  SecondaryAutomationDocumentStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        ManagementAccountId: !Ref ManagementAccountId
        TargetOUs: !Ref TargetOUs
        TargetRegions: !Ref TargetRegions
      TemplateURL: https://sql-lts-cfn-templates.s3-ap-southeast-2.amazonaws.com/SQLServerLTS-SecondaryAutomationDocument.yaml
  PrimaryAutomationDocumentStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        TagKey : !Ref TagKey
        TagValue : !Ref TagValue
      TemplateURL: https://sql-lts-cfn-templates.s3-ap-southeast-2.amazonaws.com/SQLServerLTS-PrimaryAutomationDocument.yaml
Parameters:
  OrganizationId:
    Description: AWS Organization ID.
    Type: String
    AllowedPattern: '^[o]+(-[a-z0-9]+)*$'
    ConstraintDescription: Provide a valid Organization ID (for eg. o-abc5drtefg)
  TargetOUs:
    Description: Organization Unit (OU) IDs which are in scope for this solution in a comma-separated format (for eg. ou-abc1-abc12ab1,ou-def2-def12de1).
    Type: String
    Default: ou-abc1-abc12ab1
  TargetRegions:
    Type: String
    Description: AWS Regions that is in scope for this solution in comma-separated format (for eg. ap-southeast-2, us-east-1).
    Default: ap-southeast-2,us-east-1
  TagKey:
    Description: (Required) This parameter is required if you want to target all managed instances using tags
    Type: String
    Default: 'LicenseTrackingSolution-ManagedInstance'
  TagValue:
    Description: (Required) This parameter is required if you want to target all managed instances using tags
    Type: String
    Default: 'true'
  ManagementAccountId:
    Description: (Required) Management/Root AWS Account ID from where this solution will be executed. If you are using AWS Organizations then you need to specify the root/management account.
    Type: String
    Default: '123456789012'
  BucketName:
    Description: Name for the S3 bucket that will be used to aggregate the Inventory data.
    Type: String
    AllowedPattern: '^[a-z]+(-[a-z]+)*$'
    ConstraintDescription: Provide a valid name for S3 bucket
  BucketRegion:
    Description: AWS Region where the S3 bucket should be deployed into, for eg. ap-southeast-2
    Type: String